/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package ui;

import Entity.User;
import javax.swing.*;
import java.io.File;
import java.util.List;
import com.google.gson.Gson;
import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import java.net.MalformedURLException;
import java.net.URL;
import java.io.IOException;
import java.io.InputStream;
import java.net.HttpURLConnection;
import java.util.ArrayList;
import dao.AddressDAO;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import static ui.mainform.user;
import utils.Check;

/**
 *
 * @author ACER
 */
public class NewAddress extends javax.swing.JDialog {

    /**
     * Creates new form NewAddress
     */
    public NewAddress(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        loadDataFromJSON();
        setLocationRelativeTo(null);
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JdlDangNhap = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        bntXacNhanAddress = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        JcbDuong = new javax.swing.JComboBox<>();
        JcbThanhPho = new javax.swing.JComboBox<>();
        JcbQuan = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        JdlDangNhap.setBackground(new java.awt.Color(255, 255, 255));
        JdlDangNhap.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setText("ĐỊA CHỈ GIAO HÀNG");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, -1));

        jLabel10.setBackground(new java.awt.Color(0, 0, 0));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("TỈNH / THÀNH PHỐ");
        jLabel10.setAutoscrolls(true);
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 170, 30));

        bntXacNhanAddress.setBackground(new java.awt.Color(25, 135, 84));
        bntXacNhanAddress.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bntXacNhanAddress.setForeground(new java.awt.Color(255, 255, 255));
        bntXacNhanAddress.setText("XÁC NHẬN");
        bntXacNhanAddress.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bntXacNhanAddressMouseClicked(evt);
            }
        });
        bntXacNhanAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntXacNhanAddressActionPerformed(evt);
            }
        });
        jPanel1.add(bntXacNhanAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 370, 176, 50));

        jLabel13.setBackground(new java.awt.Color(0, 0, 0));
        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("TÊN ĐƯỜNG");
        jLabel13.setAutoscrolls(true);
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 140, 30));

        jLabel14.setBackground(new java.awt.Color(0, 0, 0));
        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("QUẬN / HUYỆN");
        jLabel14.setAutoscrolls(true);
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 140, 30));

        JcbDuong.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(JcbDuong, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, 400, -1));

        JcbThanhPho.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(JcbThanhPho, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 400, -1));

        JcbQuan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        JcbQuan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JcbQuanMouseClicked(evt);
            }
        });
        jPanel1.add(JcbQuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 400, -1));

        JdlDangNhap.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 68, 630, 510));

        jLabel6.setText("Trang Chủ/");
        JdlDangNhap.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 17, -1, -1));

        jLabel7.setForeground(new java.awt.Color(0, 204, 51));
        jLabel7.setText("Thêm  mới địa chỉ");
        JdlDangNhap.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 17, 110, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(JdlDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 940, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(JdlDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bntXacNhanAddressMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bntXacNhanAddressMouseClicked
        String ThanhPho = (String) JcbThanhPho.getSelectedItem();
        String Quan = (String) JcbQuan.getSelectedItem();
        String Duong = (String) JcbDuong.getSelectedItem();
        AddressDAO addressDao = new AddressDAO();
        User u = new User();
        u = Check.user;
        addressDao.insert(Integer.parseInt(u.getId()) ,ThanhPho, Quan, Duong);
        
        this.dispose();
    }//GEN-LAST:event_bntXacNhanAddressMouseClicked

    private void bntXacNhanAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntXacNhanAddressActionPerformed

    }//GEN-LAST:event_bntXacNhanAddressActionPerformed

    private void JcbQuanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JcbQuanMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_JcbQuanMouseClicked
    private void loadDataFromJSON() {
        try {
            URL url = new URL("https://raw.githubusercontent.com/kenzouno1/DiaGioiHanhChinhVN/master/data.json");
            HttpURLConnection connection = (HttpURLConnection) url.openConnection();
            connection.setRequestMethod("GET");

            InputStream inputStream = connection.getInputStream();
            Gson gson = new Gson();
            JsonArray jsonArray = gson.fromJson(new String(inputStream.readAllBytes()), JsonArray.class);

           List<String> provinces = new ArrayList<>();
            for (JsonElement jsonElement : jsonArray) {
                JsonObject province = jsonElement.getAsJsonObject();
                provinces.add(province.get("Name").getAsString());
            }
            JcbThanhPho.setModel(new DefaultComboBoxModel<>(provinces.toArray(new String[0])));
        
            JcbThanhPho.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    int selectedIndex = JcbThanhPho.getSelectedIndex();
                    JsonObject selectedProvince = jsonArray.get(selectedIndex).getAsJsonObject();
                    JsonArray districts = selectedProvince.getAsJsonArray("Districts");

                    List<String> districts_list = new ArrayList<>();
                    for (JsonElement districtElement : districts) {
                        JsonObject district = districtElement.getAsJsonObject();
                        districts_list.add(district.get("Name").getAsString());
                    }
                    JcbQuan.setModel(new DefaultComboBoxModel<>(districts_list.toArray(new String[0])));

                    JcbQuan.addActionListener(new ActionListener() {
                        @Override
                        public void actionPerformed(ActionEvent e2) {
                            int selectedDistrictIndex = JcbQuan.getSelectedIndex();
                            JsonObject selectedDistrict = districts.get(selectedDistrictIndex).getAsJsonObject();
                            JsonArray wards = selectedDistrict.getAsJsonArray("Wards");

                            List<String> wards_list = new ArrayList<>();
                            for (JsonElement wardElement : wards) {
                                JsonObject ward = wardElement.getAsJsonObject();
                                wards_list.add(ward.get("Name").getAsString());
                            }
                            JcbDuong.setModel(new DefaultComboBoxModel<>(wards_list.toArray(new String[0])));
                        }
                    });
                }
            });
        } catch (IOException e) {
            e.printStackTrace();
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws MalformedURLException, IOException {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewAddress.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewAddress.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewAddress.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewAddress.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NewAddress dialog = new NewAddress(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> JcbDuong;
    private javax.swing.JComboBox<String> JcbQuan;
    private javax.swing.JComboBox<String> JcbThanhPho;
    private javax.swing.JPanel JdlDangNhap;
    private javax.swing.JButton bntXacNhanAddress;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
